project:
  type: book

resources: 
  - js/**
  - css/**
  - assets/**

book:
  title: "Unlawful Laws"
  author: "Dan Li (李丹)"
  description: "A Philosopher’s Footnotes to *The Three-Body Problem*"
  chapters:
    - index.qmd
    ##- intro.qmd

    - part: "Part I - When Laws Fail"
      chapters: 
        - chapters/part1/ch1_physics-never-existed.qmd
        - chapters/part1/ch2_induction-at-the-edge.qmd
        - chapters/part1/ch3_grue-machines-predictions.qmd

    - part: "Part II - Modeling the Unlawful"
      chapters: 
        - chapters/part2/ch4_false-heavens.qmd
        - chapters/part2/ch5_computability-and-chaos.qmd

    - part: "Part III - Living Beyond Law"
      chapters:
        - chapters/part3/ch6_fragile-vs-antifragile.qmd
        - chapters/part3/ch7_defending-society.qmd
        - chapters/part3/ch8_strategies-for-uncertainty.qmd

    - data/references.qmd
  site-url: https://dan-li-o.github.io/3body
  repo-url: https://github.com/dan-li-o/3body
  language: en
  sidebar: 
    style: "floating"

format:
  html:
    theme: cosmo
    html-math-method: katex
    toc: true
    number-sections: true
    code-copy: true
    css: 
      - css/widgets.css
    include-after-body:
      - text: |
          <!-- Site-wide utils only; page widgets load per-chapter -->
          <script src="/js/widgets-core.js"></script>

# Citations
bibliography: data/references.bib
# If you want Chicago notes style, add a CSL and uncomment:
# csl: data/chicago-note-bibliography.csl
link-citations: true
# Put citation details in footnotes (HTML will render them as footnotes per page)
citation-location: footnote
# Optional: show per-chapter References sections
# book:
#   chapter-bibliography: true

crossref:
  custom:
    - kind: float
      reference-prefix: Widget
      key: wid
      caption-prefix: Widget
      caption-location: bottom
      space-before-numbering: true

editor: 
  render-on-save: true
